runners:
  sh: ["/bin/bash", "-c", "$SNIP"]
  url: ["open", "$SNIP"]
  js: ["node", "-e", "$SNIP"]
  py: ["python", "-c", "$SNIP"]
  php: ["php", "-r", "$SNIP"]
  scpt: ["osascript", "-e", "$SNIP"]
  applescript: ["osascript", "-e", "$SNIP"]
  xml: ["echo", "$SNIP"]
  json: ["echo", "$SNIP"]
  java:
    compile: ["javac", "$FULL_NAME"]
    run: ["java", "$CLASS_NAME"]
  cs:
    compile: ["dotnet core only"]
    run: [""]
  go:
    run: ["go", "run", "$FULL_NAME"]
  rs:
    compile: ["rustc", "-o", "$NAME", "$FULL_NAME"]
    run: ["$NAME"]
  scala:
    compile: ["scalac", "-d", "$CACHE_DIR", "$FULL_NAME"]
    run: ["scala", "$NAME"]
  default: ["echo", "$SNIP"]
apps:
  webstorm: ["open", "-a", "webstorm", "$DIR_NAME"]
  textedit: ["open", "-e", "$FULL_NAME"]
  vi: ["vi"]
  default: ["open", "-t", "$FULL_NAME"]
editors:
  sh:
    - webstorm
    - textedit
  go:
    - gogland
    - webstorm
  java:
    -  androidstudio
  url: textedit
  default: textedit